const actiontypes = {
  GET_FIELDS: 'GET_FIELDS',
  GET_FIELDS_REQUEST: 'GET_FIELDS_REQUEST',
  GET_FIELDS_ERROR: 'GET_FIELDS_ERROR',
  DELETE_FIELD: 'DELETE_FIELD',
  RESTORE_FIELD: 'RESTORE_FIELD',
  RESET_FIELDS: 'RESET_FIELDS',
  UPDATE_FIELDS: 'UPDATE_FIELDS',
  SAVE_FIELDS: 'SAVE_FIELDS',
  SAVE_FIELDS_REQUEST: 'SAVE_FIELDS_REQUEST',
  SAVE_FIELDS_ERROR: 'SAVE_FIELDS_ERROR'
}

export {
  actiontypes
}